// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-Q-F9cAko15nc5B4CdNt_3TT_Atxngg',
    appId: '1:56793715512:web:d08e421c6dabe2009ea7cd',
    messagingSenderId: '56793715512',
    projectId: 'focus-io',
    authDomain: 'focus-io.firebaseapp.com',
    storageBucket: 'focus-io.appspot.com',
    measurementId: 'G-7WXX44P998',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3DKl8pjPb5xgKkvjwKOw1-SH6rMNguBQ',
    appId: '1:56793715512:android:6cb834ab46964f4e9ea7cd',
    messagingSenderId: '56793715512',
    projectId: 'focus-io',
    storageBucket: 'focus-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDflRXerwnr-s-KYTeq3VFFBWRrCNzbfw',
    appId: '1:56793715512:ios:5fea96d3654550269ea7cd',
    messagingSenderId: '56793715512',
    projectId: 'focus-io',
    storageBucket: 'focus-io.appspot.com',
    iosClientId: '56793715512-gae04frdc0iiahn7o7m1hb3cinl2aopc.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDflRXerwnr-s-KYTeq3VFFBWRrCNzbfw',
    appId: '1:56793715512:ios:5fea96d3654550269ea7cd',
    messagingSenderId: '56793715512',
    projectId: 'focus-io',
    storageBucket: 'focus-io.appspot.com',
    iosClientId: '56793715512-gae04frdc0iiahn7o7m1hb3cinl2aopc.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusIo',
  );
}
